-- Superseded by:
--   supabase/migrations/20260411140000_conversations_and_chat_messages.sql
--   supabase/sql/conversations_and_chat_messages_complete.sql
--
-- If you created policies manually earlier, run the “drop policy / create policy”
-- block from conversations_and_chat_messages_complete.sql so names align.
